language: node_js
node_js:
  - 13

script:
  - yarn run build

branches:
  only:
    - master

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_WEBSITE_BUCKET
  skip_cleanup: true
  region: "eu-west-1"
  local_dir: "build"
