dist: trusty
language: minimal

before_script:
  - curl -s -L https://github.com/getzola/zola/releases/download/v$ZOLA_VERSION/zola-v$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin

script:
  - zola build

branches:
  only:
    - master

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_WEBSITE_BUCKET
  skip_cleanup: true
  region: "eu-west-1"
  local_dir: "public"
